### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Kashoid23** [lime666/RubyHW_21#2]
Please replace "fourty_two" in all cases to "forty_two".
You made a mistake in the word.

Should be "forty" instead of "fourty"

https://github.com/lime666/RubyHW_21/blob/master/HW3/lib/fourty_two.rb#L1

**Comment by lime666** [comment]
> Please replace "fourty_two" in all cases to "forty_two". You made a mistake in the word.
> 
> Should be "forty" instead of "fourty"
> 
> https://github.com/lime666/RubyHW_21/blob/master/HW3/lib/fourty_two.rb#L1

I know that both ways are acceptable.

**Comment by Kashoid23** [comment]
Sorry, but I don't think so. Can you send a link to the rule? 😄 

<img width="1414" alt="Screenshot 2021-12-28 at 09 36 46" src="https://user-images.githubusercontent.com/46579145/147540931-5f217be1-d5cb-4d2c-aea6-5e51a85831b8.png">
<img width="1417" alt="Screenshot 2021-12-28 at 09 36 36" src="https://user-images.githubusercontent.com/46579145/147540938-71ef894b-1ded-4a6c-a761-8dd3bdabb45d.png">

**Comment by Kashoid23** [comment]
@lime666 This is not a critical mistake, but the RubyMine does not like it

<img width="603" alt="Screenshot 2021-12-28 at 09 41 45" src="https://user-images.githubusercontent.com/46579145/147541318-be749f71-34a9-40f2-a85a-6f45f7113733.png">

**Comment by lime666** [comment]
> Sorry, but I don't think so. Can you send a link to the rule? smile
> 
> <img alt="Screenshot 2021-12-28 at 09 36 46" width="1414" src="https://user-images.githubusercontent.com/46579145/147540931-5f217be1-d5cb-4d2c-aea6-5e51a85831b8.png">
> 
> <img alt="Screenshot 2021-12-28 at 09 36 36" width="1417" src="https://user-images.githubusercontent.com/46579145/147540938-71ef894b-1ded-4a6c-a761-8dd3bdabb45d.png">

It is an older form of this word. I know that the most common rule nowadays is to use form "forty," but I don't see in "fourty" a crucial mistake.

**Comment by Kashoid23** [comment]
Please update it
